FROM alpine:3.18

# Instalar cliente de PostgreSQL
RUN apk add --no-cache postgresql15-client

# Crear carpetas de trabajo
RUN mkdir -p /backups /scripts /var/log

# Copiar los scripts de backup, limpieza y arranque
COPY backup.sh /scripts/
COPY cleaner.sh /scripts/
COPY entrypoint.sh /scripts/

# Dar permisos de ejecución
RUN chmod +x /scripts/backup.sh /scripts/cleaner.sh /scripts/entrypoint.sh

# Ejecutar el script de entrada
CMD ["/scripts/entrypoint.sh"]